version: '2'
services:
    jhipstersamplemicroservice-app:
        image: jhipstersamplemicroservice
        external_links:
            - jhipstersamplemicroservice-postgresql:postgresql
            - jhipster-registry:registry
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_CLOUD_CONFIG_URI=http://admin:admin@registry:8761/config
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/jhipsterSampleMicroservice
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    jhipstersamplemicroservice-postgresql:
        extends:
            file: postgresql.yml
            service: jhipstersamplemicroservice-postgresql
    jhipster-registry:
        extends:
            file: jhipster-registry.yml
            service: jhipster-registry
        environment:
            - SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS=file:./central-config/docker-config/
