version: '2'
services:
    jhipstersamplemicroservice-postgresql:
        image: postgres:9.6.2
        # volumes:
        #     - ~/volumes/jhipster/jhipsterSampleMicroservice/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=jhipsterSampleMicroservice
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
