version: '2'
services:
    jhipstersamplemicroservice-sonar:
        container_name: jhipstersamplemicroservice-sonar
        image: sonarqube:6.0-alpine
        ports:
            - 9000:9000
            - 9092:9092
